### ISSUE TITLE
need more good photo's

### ISSUE THREAD

**Issue by despiegk** [codescalers/www-new-greencharters#3]
inside/outside
in galleries
can be deeper in site. think about best structure

**Comment by despiegk** [comment]
will give instructions what to reuse

**Comment by despiegk** [comment]
[scan0006.pdf](https://github.com/codescalers/www-new-greencharters/files/248996/scan0006.pdf)

on the 3 main sections
- sail
- play
- relax
few photos & they need to be perfect

on the info page we can have multiple galleries or links to galleries and other fotos can be there
only use the good fotos
we have recommended some in this attachment which for sure we should not use

**Comment by karimal** [comment]
[Moved](https://github.com/Incubaid/www_greenboats/issues/8)
