### ISSUE TITLE
new structure

### ISSUE THREAD

**Issue by despiegk** [codescalers/www-new-greencharters#4]
![image](https://cloud.githubusercontent.com/assets/6021844/15017738/e2c080f6-1227-11e6-831c-d83caa1478bd.png)

menu structure
- sail
- play
- relax
- specs (call info in menu)

as 4 topics

the specs is link to detailed galleries

sail-play-relax are high level just like in midori site

**Comment by karimal** [comment]
[Moved](https://github.com/Incubaid/www_greenboats/issues/3)
